language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - rustup component add rustfmt
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --check
branches:
  only:
    - master # Pushes and PRs to master
notifications:
  email:
    on_success: never
