[package]
name = "ynq"
description = "A very simple utility to ask a yes/no question"
version = "0.1.0"
authors = ["Joseph Egan <joseph.s.egan@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = "2.33.0"
rprompt = "1.0.5"
